hotfix: Corregir NameError 'subareas' en dashboard_aprobaciones
- Línea 1366: cambiar 'subareas' por 'areas'
- La variable correcta es 'areas' (definida en línea 1356-1360)
- Segundo error en la misma función después del fix anterior

Error en producción:
NameError: name 'subareas' is not defined. Did you mean: 'SubArea'?

Relacionado: commit bc24ebd, f758d17